// import './page/eventLoop/index'
// import './page/eventLoop/1'
// import './page/strictEqual'
// import './page/writeJs/new'
// import './page/writeJs/call'
// import './page/writeJs/apply'
// import './page/writeJs/bind'
// import './page/writeJs/extend'
import './page/writeJs/curry'